services:
  # FastAPI 애플리케이션
  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    volumes:
      - ./fastapi-logs:/var/log/fastapi
    restart: unless-stopped
    networks:
      - loki-network

  # Nginx 리버스 프록시
  nginx:
    image: nginx:1.21-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-logs:/var/log/nginx
    command: >
      /bin/sh -c "mkdir -p /var/log/nginx &&
                  touch /var/log/nginx/access.log /var/log/nginx/error.log &&
                  chmod 644 /var/log/nginx/access.log /var/log/nginx/error.log &&
                  nginx -g 'daemon off;'"
    depends_on:
      - fastapi
    restart: unless-stopped
    networks:
      - loki-network

  # Loki - 로그 저장소
  loki:
    image: grafana/loki:2.8.2
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - ./loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    user: "0:0"  # root 권한으로 실행하여 권한 문제 해결
    restart: unless-stopped
    networks:
      - loki-network

  # Promtail - 로그 수집기
  promtail:
    image: grafana/promtail:2.8.2
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yml
      - ./fastapi-logs:/var/log/fastapi:ro
      - ./nginx-logs:/var/log/nginx:ro
      - ./promtail-data:/promtail
    command: -config.file=/etc/promtail/config.yml
    user: "0:0"  # root 권한으로 실행하여 권한 문제 해결
    depends_on:
      - loki
      - fastapi
      - nginx
    restart: unless-stopped
    networks:
      - loki-network

  # Grafana - 시각화
  grafana:
    image: grafana/grafana:9.5.2
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - ./grafana-data:/var/lib/grafana
    depends_on:
      - loki
    restart: unless-stopped
    networks:
      - loki-network

networks:
  loki-network:
    driver: bridge